# Generated by Django 5.2.10 on 2026-01-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboardaggregate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardaggregate',
            new_name='dashboard_d_company_83808b_idx',
            old_name='dashboard_a_company_2b34cb_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardsnapshot',
            new_name='dashboard_d_company_d187bd_idx',
            old_name='dashboard_s_company_86f1f6_idx',
        ),
    ]
