# Generated by Django 5.2.10 on 2026-01-22 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0002_proyecto_projects_progress_pct_0_100_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['company', 'sitec', '-created_at'], name='projects_pr_company_04a39a_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='projects_pr_status_b34284_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['company', 'sitec', 'status'], name='projects_pr_company_e91c42_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['created_at'], name='projects_pr_created_59abf1_idx'),
        ),
    ]
