# Generated by Django 5.2.10 on 2026-01-18 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('text', 'Text')], max_length=20)),
                ('hash', models.CharField(max_length=128)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='aisuggestion',
            new_name='ai_aisugges_company_7ef4c0_idx',
            old_name='ai_aisugge_company_5ea938_idx',
        ),
        migrations.RenameIndex(
            model_name='aisuggestion',
            new_name='ai_aisugges_model_n_33bc82_idx',
            old_name='ai_aisugge_model_n_676a91_idx',
        ),
        migrations.RenameIndex(
            model_name='aisuggestion',
            new_name='ai_aisugges_status_201c28_idx',
            old_name='ai_aisugge_status__6c1f05_idx',
        ),
        migrations.AddField(
            model_name='aiasset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='aiasset',
            name='sitec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.sitec'),
        ),
        migrations.AddField(
            model_name='aiasset',
            name='suggestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aisuggestion'),
        ),
        migrations.AddField(
            model_name='aiasset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiasset',
            index=models.Index(fields=['company', 'sitec', '-created_at'], name='ai_aiasset_company_6e7b34_idx'),
        ),
        migrations.AddIndex(
            model_name='aiasset',
            index=models.Index(fields=['asset_type'], name='ai_aiasset_asset_t_0f459c_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiasset',
            constraint=models.UniqueConstraint(fields=('company', 'hash'), name='ai_asset_unique_hash_per_company'),
        ),
    ]
