# Generated by Django 5.2.10 on 2026-01-27 16:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions_cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.UUIDField(db_column='id_transaccion', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Transacción')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la transacción (debe ser mayor a 0)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('ARS', 'ARS'), ('BRL', 'BRL'), ('CLP', 'CLP'), ('COP', 'COP'), ('PEN', 'PEN')], default='MXN', help_text='Código ISO 4217 de la moneda (3 caracteres)', max_length=3, verbose_name='Moneda')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la transacción', verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('fallida', 'Fallida')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='transactions.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transactions_transaccion',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['id_cliente', '-fecha'], name='transaccion_cliente_fecha_idx'), models.Index(fields=['estado', '-fecha'], name='transaccion_estado_fecha_idx'), models.Index(fields=['moneda', '-fecha'], name='transaccion_moneda_fecha_idx'), models.Index(fields=['-fecha'], name='transaccion_fecha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='transaccion_monto_positivo'), models.CheckConstraint(condition=models.Q(('estado__in', ['pendiente', 'completada', 'cancelada', 'fallida'])), name='transaccion_estado_valido')],
            },
        ),
    ]
