# Generated by Django 5.2.10 on 2026-01-18 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('version', models.IntegerField(default=1)),
                ('scope', models.CharField(choices=[('wizard', 'Wizard'), ('report', 'Report')], default='wizard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('sitec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.sitec')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('field', models.CharField(blank=True, max_length=80)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('condition', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rules.ruleset')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddIndex(
            model_name='ruleset',
            index=models.Index(fields=['company', 'sitec', 'scope', '-created_at'], name='rules_rules_company_9db536_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ruleset',
            unique_together={('company', 'sitec', 'scope', 'version')},
        ),
        migrations.AddIndex(
            model_name='ruleitem',
            index=models.Index(fields=['ruleset', 'step', 'severity'], name='rules_rulei_ruleset_82d61c_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleitem',
            index=models.Index(fields=['code'], name='rules_rulei_code_d6c0b8_idx'),
        ),
    ]
