# Generated by Django 5.2.10 on 2026-01-17 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSemanal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField(help_text='Inicio de semana del reporte')),
                ('week_end', models.DateField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=200)),
                ('site_address', models.TextField()),
                ('progress_pct', models.IntegerField(default=0, help_text='Porcentaje de avance 0-100')),
                ('schedule_status', models.CharField(blank=True, max_length=50)),
                ('cabling_nodes_total', models.IntegerField(blank=True, null=True)),
                ('cabling_nodes_ok', models.IntegerField(blank=True, null=True)),
                ('racks_installed', models.IntegerField(blank=True, null=True)),
                ('security_devices', models.IntegerField(blank=True, null=True)),
                ('materials_count', models.IntegerField(blank=True, null=True)),
                ('tests_passed', models.BooleanField(blank=True, null=True)),
                ('qa_signed', models.BooleanField(default=False)),
                ('incidents', models.BooleanField(default=False)),
                ('incidents_count', models.IntegerField(default=0)),
                ('incidents_severity', models.CharField(blank=True, max_length=20)),
                ('incidents_detail', models.TextField(blank=True)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('wizard_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('riesgo_score', models.FloatField(blank=True, help_text='Score de riesgo calculado por IA', null=True)),
                ('sugerencias_ia', models.JSONField(blank=True, default=list)),
                ('predicciones', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='draft', max_length=20)),
                ('signature_tech', models.TextField(blank=True)),
                ('signature_supervisor', models.TextField(blank=True)),
                ('signature_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='projects.proyecto')),
                ('sitec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.sitec')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_supervisor', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='medium', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='reports.reportesemanal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('photo', 'Fotografía'), ('document', 'Documento'), ('video', 'Video'), ('audio', 'Audio')], default='photo', max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reports.reportesemanal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportesemanal',
            index=models.Index(fields=['company', '-week_start'], name='reports_rep_company_954d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesemanal',
            index=models.Index(fields=['technician', '-week_start'], name='reports_rep_technic_fecf11_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesemanal',
            index=models.Index(fields=['status', '-created_at'], name='reports_rep_status_65d2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesemanal',
            index=models.Index(fields=['project', '-week_start'], name='reports_rep_project_8279c3_idx'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['reporte', 'severity'], name='reports_inc_reporte_9a81a4_idx'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['resolved', '-created_at'], name='reports_inc_resolve_eba2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['reporte', '-created_at'], name='reports_evi_reporte_e884d9_idx'),
        ),
    ]
