# Generated by Django 5.2.10 on 2026-01-17 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('syncing', 'Sincronizando'), ('completed', 'Completada'), ('failed', 'Fallida'), ('conflict', 'Conflicto')], default='pending', max_length=20)),
                ('items_synced', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('conflicts_detected', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('sitec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.sitec')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('synced', 'Sincronizado'), ('failed', 'Fallido'), ('conflict', 'Conflicto')], default='pending', max_length=20)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sync.syncsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(fields=['company', 'user', '-started_at'], name='sync_syncse_company_18c7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(fields=['status', '-started_at'], name='sync_syncse_status_26b2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='syncitem',
            index=models.Index(fields=['session', 'status'], name='sync_syncit_session_532429_idx'),
        ),
        migrations.AddIndex(
            model_name='syncitem',
            index=models.Index(fields=['entity_type', 'entity_id'], name='sync_syncit_entity__663376_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncitem',
            unique_together={('session', 'entity_type', 'entity_id')},
        ),
    ]
