# Generated by Django 5.2.10 on 2026-01-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roi', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roisnapshot',
            new_name='roi_roisnap_company_923f33_idx',
            old_name='roi_snapsho_company_4ddcaa_idx',
        ),
    ]
