# Generated by Django 5.2.10 on 2026-01-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_company_45ca0d_idx',
            old_name='documents_do_company_06d4df_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_report__ecad5f_idx',
            old_name='documents_do_report__f2f498_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_status_dead80_idx',
            old_name='documents_do_status_78ab1b_idx',
        ),
    ]
