# Generated by Django 5.2.10 on 2026-01-17 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiSuggestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("step", models.IntegerField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("quick", "Quick"), ("heavy", "Heavy"), ("fallback", "Fallback")],
                        default="quick",
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(default="rule_engine", max_length=100)),
                ("model_version", models.CharField(default="v1", max_length=50)),
                ("input_snapshot", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("fallback", "Fallback"), ("queued", "Queued"), ("error", "Error")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.company")),
                ("sitec", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="companies.sitec")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(fields=["company", "sitec", "-created_at"], name="ai_aisugge_company_5ea938_idx"),
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(fields=["model_name", "model_version"], name="ai_aisugge_model_n_676a91_idx"),
        ),
        migrations.AddIndex(
            model_name="aisuggestion",
            index=models.Index(fields=["status", "-created_at"], name="ai_aisugge_status__6c1f05_idx"),
        ),
    ]
