# Generated by Django 5.2.10 on 2026-01-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_ai_training_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aitrainingjob',
            new_name='ai_aitraini_company_161d4d_idx',
            old_name='ai_aitrainingjob_company_sitec_created',
        ),
        migrations.RenameIndex(
            model_name='aitrainingjob',
            new_name='ai_aitraini_status_7a5390_idx',
            old_name='ai_aitrainingjob_status_created',
        ),
        migrations.AlterField(
            model_name='aitrainingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dataset_ready', 'Dataset Ready'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
