# Generated by Django 5.2.10 on 2026-01-22 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0003_add_performance_indexes'),
        ('reports', '0003_reportesemanal_rules_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportesemanal',
            index=models.Index(fields=['company', 'sitec', '-week_start'], name='reports_rep_company_a7b2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesemanal',
            index=models.Index(fields=['company', 'sitec', 'status', '-created_at'], name='reports_rep_company_45c2de_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesemanal',
            index=models.Index(fields=['week_start'], name='reports_rep_week_st_c250c3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportesemanal',
            index=models.Index(fields=['created_at'], name='reports_rep_created_5788f9_idx'),
        ),
    ]
