# Generated by Django 5.2.10 on 2026-01-18 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0002_proyecto_projects_progress_pct_0_100_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesemanal',
            name='wizard_client_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reportesemanal',
            name='wizard_schema_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reportesemanal',
            name='wizard_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='evidencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__gte', -90), ('latitude__lte', 90)), ('latitude__isnull', True), _connector='OR'), name='evidencia_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='evidencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('longitude__gte', -180), ('longitude__lte', 180)), ('longitude__isnull', True), _connector='OR'), name='evidencia_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='reportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('progress_pct__gte', 0), ('progress_pct__lte', 100)), name='reports_progress_pct_0_100'),
        ),
        migrations.AddConstraint(
            model_name='reportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('cabling_nodes_total__gte', 0), ('cabling_nodes_total__isnull', True), _connector='OR'), name='reports_cabling_nodes_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('materials_count__gte', 0), ('materials_count__isnull', True), _connector='OR'), name='reports_materials_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('security_devices__gte', 0), ('security_devices__isnull', True), _connector='OR'), name='reports_security_devices_non_negative'),
        ),
    ]
