# Generated by Django 5.2.10 on 2026-01-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportesemanal_wizard_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesemanal',
            name='rules_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
