# Generated by Django 5.2.10 on 2026-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesemanal',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
