# Generated by Django 5.2.10 on 2026-01-17 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Código único del proyecto', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('site_address', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_contact', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planificación'), ('in_progress', 'En Progreso'), ('on_hold', 'En Pausa'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='planning', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('progress_pct', models.IntegerField(default=0, help_text='Porcentaje de avance 0-100')),
                ('budget_estimated', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto estimado (MXN)', max_digits=12, null=True)),
                ('budget_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto actual (MXN)', max_digits=12, null=True)),
                ('riesgo_score', models.FloatField(blank=True, help_text='Score de riesgo calculado por IA', null=True)),
                ('sugerencias_ia', models.JSONField(blank=True, default=list)),
                ('predicciones', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_pm', to=settings.AUTH_USER_MODEL)),
                ('sitec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.sitec')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_supervisor', to=settings.AUTH_USER_MODEL)),
                ('technicians', models.ManyToManyField(blank=True, related_name='proyectos_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('materiales', 'Materiales'), ('mano_obra', 'Mano de Obra'), ('equipamiento', 'Equipamiento'), ('servicios', 'Servicios'), ('otros', 'Otros')], max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('amount_estimated', models.DecimalField(decimal_places=2, help_text='Monto estimado (MXN)', max_digits=12)),
                ('amount_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Monto actual (MXN)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='projects.proyecto')),
            ],
            options={
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='medium', max_length=20)),
                ('probability', models.CharField(choices=[('very_low', 'Muy Baja'), ('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('very_high', 'Muy Alta')], default='medium', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('mitigation_status', models.CharField(choices=[('not_started', 'No Iniciada'), ('in_progress', 'En Progreso'), ('completed', 'Completada')], default='not_started', max_length=20)),
                ('riesgo_score', models.FloatField(blank=True, help_text='Score calculado por IA', null=True)),
                ('sugerencias_ia', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='projects.proyecto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('blocked', 'Bloqueada')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='projects.proyecto')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['company', 'status'], name='projects_pr_company_102807_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['project_manager', '-created_at'], name='projects_pr_project_a72c03_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['code'], name='projects_pr_code_8a8fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['start_date', 'end_date'], name='projects_pr_start_d_f4b037_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuesto',
            index=models.Index(fields=['project', 'category'], name='projects_pr_project_5078b6_idx'),
        ),
        migrations.AddIndex(
            model_name='riesgo',
            index=models.Index(fields=['project', 'severity'], name='projects_ri_project_38c898_idx'),
        ),
        migrations.AddIndex(
            model_name='riesgo',
            index=models.Index(fields=['mitigation_status'], name='projects_ri_mitigat_6f1d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['project', 'status'], name='projects_ta_project_f0c39a_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['assigned_to', 'status'], name='projects_ta_assigne_5d8ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['due_date'], name='projects_ta_due_dat_d27fe9_idx'),
        ),
    ]
