# Generated by Django 5.2.10 on 2026-01-18 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.CheckConstraint(condition=models.Q(('progress_pct__gte', 0), ('progress_pct__lte', 100)), name='projects_progress_pct_0_100'),
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.CheckConstraint(condition=models.Q(('budget_estimated__gte', 0), ('budget_estimated__isnull', True), _connector='OR'), name='projects_budget_estimated_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.CheckConstraint(condition=models.Q(('budget_actual__gte', 0), ('budget_actual__isnull', True), _connector='OR'), name='projects_budget_actual_non_negative'),
        ),
    ]
